In [1]:
import torch

In [2]:
def print_val(x):
    print ("Type: ", type(x))
    print ("Shape: ", x.shape)
    print ("Value: \n", x)
    print (" ")

In [3]:
x = torch.rand(2, 3, 2) # uniform random : 0~1, all numbers have same probability
print_val(x) # 2x3x2 tensor(3 dimension), value should be 'real number'
#type : 'torch.Tensor', numpy -> 'numpy.ndarray'
#shape : torch.Size, numpy -> (, )

x = torch.randn(2, 3) # Gaussian : random values follow 'Gaussian distribution'
print_val(x) # 2x3 tensor(Matrix)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3, 2])
Value: 
 tensor([[[0.7380, 0.0719],
         [0.7183, 0.2576],
         [0.6077, 0.6313]],

        [[0.2867, 0.1154],
         [0.4760, 0.6048],
         [0.6593, 0.0499]]])
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value: 
 tensor([[ 1.4601, -1.7286, -1.3587],
        [ 0.7427, -1.6481, -0.1152]])
 


In [4]:
x = torch.randperm(4) # 0~n-1(parameter), resemble with 'rand' function
print_val(x) # value should be 'integer'

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([4])
Value: 
 tensor([1, 0, 3, 2])
 


In [5]:
# divide value from 'start(0)' to 'end(3)' by 'step', and make array in order
x = torch.arange(0, 3, step = 0.5)
print_val(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([6])
Value: 
 tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
 


In [6]:
# torch function : ones, zeros
print_val(torch.ones(3,4)) # 3x4 matrix tensor
print_val(torch.zeros(3,4)) # 3x4 matrix tensor

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([3, 4])
Value: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([3, 4])
Value: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
 


In [9]:
print_val(torch.Tensor(2,4)) # make 2x4 matrix tensor, each value is random

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 4])
Value: 
 tensor([[ 0.0000e+00,  0.0000e+00, -3.2435e+38, -3.5873e-43],
        [ 6.2140e-36,  4.5909e-41,  0.0000e+00,  0.0000e+00]])
 


In [10]:
print_val(torch.Tensor([2,3])) # make vector tensor following array parameter

print_val(torch.Tensor([[2,3], [3,4]])) # make matrix tensor following array parameter

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2])
Value: 
 tensor([2., 3.])
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 2])
Value: 
 tensor([[2., 3.],
        [3., 4.]])
 


In [12]:
x = torch.FloatTensor(2,3) # make 'real number/float' type tensor
print_val(x)

x = x.type_as(torch.IntTensor()) # change tensor from 'float' type to 'Integer' type
print_val(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value: 
 tensor([[2.0000e+00, 1.2211e+05, 5.6052e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value: 
 tensor([[     2, 122112,      0],
        [     0,      0,      0]], dtype=torch.int32)
 


In [13]:
# return size of tensor
torch.FloatTensor(3, 4, 5).size()

torch.Size([3, 4, 5])

In [15]:
# make 'numpy array' and change to 'torch tensor'
import numpy as np
np_x = np.ndarray((2,3), dtype = int)
print_val(np_x)

x = torch.from_numpy(np_x)
print_val(x)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 3)
Value: 
 [[          1           0 -1500915632]
 [        411           0           0]]
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value: 
 tensor([[          1,           0, -1500915632],
        [        411,           0,           0]], dtype=torch.int32)
 
