In [6]:
import numpy as np

In [10]:
# print data type, shape, value of tensor
def print_val(x):
    print ("Type: ", type(x))
    print ("Shape: ", x.shape)
    print ("Value: \n", x)
    print (" ")

In [11]:
# rank 1 tensor : vector
x = np.array([1, 2, 3]) # array vector 
print_val(x)

x[0] = 5
print_val(x)

Type:  <class 'numpy.ndarray'>
Shape:  (3,)
Value: 
 [1 2 3]
 
Type:  <class 'numpy.ndarray'>
Shape:  (3,)
Value: 
 [5 2 3]
 


In [12]:
# rank 2 tensor : matrix
a = np.array([[1,2,3], [4,5,6]]) # 2x2 array matrix 
print_val(a)

a = np.ones((3, 2)) # 3x2 ones matrix
print_val(a)

a = np.zeros((2, 2)) # 2x2 zeros matrix
print_val(a)

a = np.eye(3,3) # 3x3 identity matrix
print_val(a)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 3)
Value: 
 [[1 2 3]
 [4 5 6]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (3, 2)
Value: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[0. 0.]
 [0. 0.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
Value: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [16]:
# random matrix
a = np.random.random((4,4)) # uniform random matrix(0~1, all value has same probability)
print_val(a)

a = np.random.randn(4,4) # gaussian random matrix(random value following gaussian distribution)
print_val(a)

Type:  <class 'numpy.ndarray'>
Shape:  (4, 4)
Value: 
 [[0.55098516 0.11264428 0.27232978 0.83081197]
 [0.47617506 0.5900495  0.70921678 0.03869018]
 [0.02285236 0.65684511 0.07951565 0.26954809]
 [0.41370377 0.83663729 0.07307894 0.84803473]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (4, 4)
Value: 
 [[-0.77142342 -0.61203584  0.16159507  1.01871363]
 [ 1.31501981 -0.0311988  -0.2687291  -2.1599512 ]
 [-1.92914001 -0.13136564 -0.42783567  0.31126262]
 [-0.87826634 -1.48053802  1.23549868  0.07934631]]
 


In [21]:
# matrix indexing(slicing)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_val(a)

b = a[:2, 1:3] # make new array by slicing matrix a
print_val(b)

row1 = a[1, :] # get 2nd row from matrix a
print_val(row1)

Type:  <class 'numpy.ndarray'>
Shape:  (3, 4)
Value: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[2 3]
 [6 7]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (4,)
Value: 
 [5 6 7 8]
 


In [25]:
# operate elements of two matrix(elementwise operating)
m1 = np.array([[1,2], [3,4]], dtype = np.float64)
m2 = np.array([[5,6], [7,8]], dtype = np.float64)

print_val(m1 + m2) # add each element of m1, m2
print_val(np.add(m1, m2)) # use function 'add'

print_val(m1 - m2) # subtract each element of m1, m2
print_val(np.subtract(m1, m2)) # use function 'subtract'

print_val(m1 * m2) # multiply each element of m1, m2
print_val(np.multiply(m1, m2)) # use function 'multiply'

print_val(m1 / m2) # divide each element of m1, m2
print_val(np.divide(m1, m2)) # use function 'divide'

print_val(np.sqrt(m1)) # get square root value by each element

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[ 6.  8.]
 [10. 12.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[ 6.  8.]
 [10. 12.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[-4. -4.]
 [-4. -4.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[-4. -4.]
 [-4. -4.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[ 5. 12.]
 [21. 32.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[ 5. 12.]
 [21. 32.]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[1.         1.41421356]
 [1.73205081 2.        ]]
 


In [31]:
# operate matrix

m1 = np.array([[1,2], [3,4]]) # 2x2
m2 = np.array([[5,6], [7,8]])
v1 = np.array([9,10]) 
v2 = np.array([11,12])

print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[1 2]
 [3 4]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[5 6]
 [7 8]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
Value: 
 [ 9 10]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
Value: 
 [11 12]
 


In [32]:
    # operate 1 'matrix multiplication'
print_val(v1.dot(v2)) # v1 = 1x2, v2 = 2x1, numpy array has function 'dot'
print_val(np.dot(v1, v2)) # result = 1x1(scalar), vector has flexible choices between vertical one and horizon one

print_val(m1.dot(v1)) # m1 = 2x2, v1 = 2x1 -> res = 2x1
print_val(np.dot(m1, v1)) 

print_val(m1.dot(m2)) # m1 = 2x2, m2 = 2x2 -> res 2x2

Type:  <class 'numpy.int32'>
Shape:  ()
Value: 
 219
 
Type:  <class 'numpy.int32'>
Shape:  ()
Value: 
 219
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
Value: 
 [29 67]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
Value: 
 [29 67]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[19 22]
 [43 50]]
 


In [33]:
    # operate 2 'transpose' : change vectors from row to column(or from column to row)
print_val(m1) 
print_val(m1.T) # ex) 1st row -> 1st column, Nrd row -> Nrd column

Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[1 2]
 [3 4]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2, 2)
Value: 
 [[1 3]
 [2 4]]
 


In [36]:
    # operate 3 'sum'
print_val(np.sum(m1)) # sum all elements -> scalar
print_val(np.sum(m1, axis=0)) # axis = direction(0 = sum elements by row direction)
print_val(np.sum(m1, axis=1)) # 1 = sum elements by column direction

# axis : N dimension tensor has N-1 axis
    # 0 : most outside dimension
    # N-1 : most inside dimension

Type:  <class 'numpy.int32'>
Shape:  ()
Value: 
 10
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
Value: 
 [4 6]
 
Type:  <class 'numpy.ndarray'>
Shape:  (2,)
Value: 
 [3 7]
 


In [44]:
m1 = np.array([[1,2,3], [4,5,6]])
print (m1)
print (m1.shape) # 2x3
print(" ")

print (np.sum(m1))
print(" ")
print (np.sum(m1, axis=0)) # 1x3
print(" ")
print (np.sum(m1, axis=1)) # 1x2

[[1 2 3]
 [4 5 6]]
(2, 3)
 
21
 
[5 7 9]
 
[ 6 15]


In [45]:
     # operate 4 'zeros-like'

m1 = np.array([[1,2,3],
              [4,5,6],
             [7,8,9],
             [10,11,12]])
m2 = np.zeros_like(m1) # m2(zeros-like) is '0' matrix has same shape with m1

print_val(m1)
print_val(m2)

Type:  <class 'numpy.ndarray'>
Shape:  (4, 3)
Value: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 
Type:  <class 'numpy.ndarray'>
Shape:  (4, 3)
Value: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
 
